/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthApiKeysIndexRouteImport } from './routes/_auth/api-keys/index'
import { Route as AuthMediaIndexRouteImport } from './routes/_auth/media/index'
import { Route as AuthPagesIndexRouteImport } from './routes/_auth/pages/index'
import { Route as AuthPagesIdRouteImport } from './routes/_auth/pages/$id'
import { Route as AuthPagesNewRouteImport } from './routes/_auth/pages/new'
import { Route as AuthPostTypesIndexRouteImport } from './routes/_auth/post-types/index'
import { Route as AuthPostTypesIdRouteImport } from './routes/_auth/post-types/$id'
import { Route as AuthPostTypesNewRouteImport } from './routes/_auth/post-types/new'
import { Route as AuthPostsIndexRouteImport } from './routes/_auth/posts/index'
import { Route as AuthPostsIdRouteImport } from './routes/_auth/posts/$id'
import { Route as AuthPostsNewRouteImport } from './routes/_auth/posts/new'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthTagsIndexRouteImport } from './routes/_auth/tags/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApiKeysIndexRoute = AuthApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMediaIndexRoute = AuthMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagesIndexRoute = AuthPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagesIdRoute = AuthPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagesNewRoute = AuthPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostTypesIndexRoute = AuthPostTypesIndexRouteImport.update({
  id: '/post-types/',
  path: '/post-types/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostTypesIdRoute = AuthPostTypesIdRouteImport.update({
  id: '/post-types/$id',
  path: '/post-types/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostTypesNewRoute = AuthPostTypesNewRouteImport.update({
  id: '/post-types/new',
  path: '/post-types/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIndexRoute = AuthPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIdRoute = AuthPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsNewRoute = AuthPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagsIndexRoute = AuthTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/pages/new': typeof AuthPagesNewRoute
  '/post-types/$id': typeof AuthPostTypesIdRoute
  '/post-types/new': typeof AuthPostTypesNewRoute
  '/posts/$id': typeof AuthPostsIdRoute
  '/posts/new': typeof AuthPostsNewRoute
  '/api-keys/': typeof AuthApiKeysIndexRoute
  '/media/': typeof AuthMediaIndexRoute
  '/pages/': typeof AuthPagesIndexRoute
  '/post-types/': typeof AuthPostTypesIndexRoute
  '/posts/': typeof AuthPostsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/tags/': typeof AuthTagsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof AuthIndexRoute
  '/pages/$id': typeof AuthPagesIdRoute
  '/pages/new': typeof AuthPagesNewRoute
  '/post-types/$id': typeof AuthPostTypesIdRoute
  '/post-types/new': typeof AuthPostTypesNewRoute
  '/posts/$id': typeof AuthPostsIdRoute
  '/posts/new': typeof AuthPostsNewRoute
  '/api-keys': typeof AuthApiKeysIndexRoute
  '/media': typeof AuthMediaIndexRoute
  '/pages': typeof AuthPagesIndexRoute
  '/post-types': typeof AuthPostTypesIndexRoute
  '/posts': typeof AuthPostsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/tags': typeof AuthTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/pages/$id': typeof AuthPagesIdRoute
  '/_auth/pages/new': typeof AuthPagesNewRoute
  '/_auth/post-types/$id': typeof AuthPostTypesIdRoute
  '/_auth/post-types/new': typeof AuthPostTypesNewRoute
  '/_auth/posts/$id': typeof AuthPostsIdRoute
  '/_auth/posts/new': typeof AuthPostsNewRoute
  '/_auth/api-keys/': typeof AuthApiKeysIndexRoute
  '/_auth/media/': typeof AuthMediaIndexRoute
  '/_auth/pages/': typeof AuthPagesIndexRoute
  '/_auth/post-types/': typeof AuthPostTypesIndexRoute
  '/_auth/posts/': typeof AuthPostsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/tags/': typeof AuthTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/pages/$id'
    | '/pages/new'
    | '/post-types/$id'
    | '/post-types/new'
    | '/posts/$id'
    | '/posts/new'
    | '/api-keys/'
    | '/media/'
    | '/pages/'
    | '/post-types/'
    | '/posts/'
    | '/settings/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/'
    | '/pages/$id'
    | '/pages/new'
    | '/post-types/$id'
    | '/post-types/new'
    | '/posts/$id'
    | '/posts/new'
    | '/api-keys'
    | '/media'
    | '/pages'
    | '/post-types'
    | '/posts'
    | '/settings'
    | '/tags'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/setup'
    | '/_auth/'
    | '/_auth/pages/$id'
    | '/_auth/pages/new'
    | '/_auth/post-types/$id'
    | '/_auth/post-types/new'
    | '/_auth/posts/$id'
    | '/_auth/posts/new'
    | '/_auth/api-keys/'
    | '/_auth/media/'
    | '/_auth/pages/'
    | '/_auth/post-types/'
    | '/_auth/posts/'
    | '/_auth/settings/'
    | '/_auth/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/api-keys/': {
      id: '/_auth/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AuthApiKeysIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/media/': {
      id: '/_auth/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthMediaIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pages/': {
      id: '/_auth/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthPagesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pages/$id': {
      id: '/_auth/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof AuthPagesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pages/new': {
      id: '/_auth/pages/new'
      path: '/pages/new'
      fullPath: '/pages/new'
      preLoaderRoute: typeof AuthPagesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/post-types/': {
      id: '/_auth/post-types/'
      path: '/post-types'
      fullPath: '/post-types/'
      preLoaderRoute: typeof AuthPostTypesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/post-types/$id': {
      id: '/_auth/post-types/$id'
      path: '/post-types/$id'
      fullPath: '/post-types/$id'
      preLoaderRoute: typeof AuthPostTypesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/post-types/new': {
      id: '/_auth/post-types/new'
      path: '/post-types/new'
      fullPath: '/post-types/new'
      preLoaderRoute: typeof AuthPostTypesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/': {
      id: '/_auth/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthPostsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/$id': {
      id: '/_auth/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof AuthPostsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/new': {
      id: '/_auth/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthPostsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tags/': {
      id: '/_auth/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthTagsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthPagesIdRoute: typeof AuthPagesIdRoute
  AuthPagesNewRoute: typeof AuthPagesNewRoute
  AuthPostTypesIdRoute: typeof AuthPostTypesIdRoute
  AuthPostTypesNewRoute: typeof AuthPostTypesNewRoute
  AuthPostsIdRoute: typeof AuthPostsIdRoute
  AuthPostsNewRoute: typeof AuthPostsNewRoute
  AuthApiKeysIndexRoute: typeof AuthApiKeysIndexRoute
  AuthMediaIndexRoute: typeof AuthMediaIndexRoute
  AuthPagesIndexRoute: typeof AuthPagesIndexRoute
  AuthPostTypesIndexRoute: typeof AuthPostTypesIndexRoute
  AuthPostsIndexRoute: typeof AuthPostsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthTagsIndexRoute: typeof AuthTagsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthPagesIdRoute: AuthPagesIdRoute,
  AuthPagesNewRoute: AuthPagesNewRoute,
  AuthPostTypesIdRoute: AuthPostTypesIdRoute,
  AuthPostTypesNewRoute: AuthPostTypesNewRoute,
  AuthPostsIdRoute: AuthPostsIdRoute,
  AuthPostsNewRoute: AuthPostsNewRoute,
  AuthApiKeysIndexRoute: AuthApiKeysIndexRoute,
  AuthMediaIndexRoute: AuthMediaIndexRoute,
  AuthPagesIndexRoute: AuthPagesIndexRoute,
  AuthPostTypesIndexRoute: AuthPostTypesIndexRoute,
  AuthPostsIndexRoute: AuthPostsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthTagsIndexRoute: AuthTagsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
